/**
 * Created by liguohua on 25/03/2017.
 */
export const APP_COPYRIGHT_INFO = "Copyright © 2016 - " + new Date().getFullYear() + " 青橙科技. All Rights Reserved.";


export const APP_SEARCH_CATEGORY_CNNAME = "APP_SEARCH_CATEGORY_CNNAME";

export const APP_SEARCH_CATEGORY_ID = "APP_SEARCH_CATEGORY_ID";

export const APP_SEARCH_CATEGORY_ICON = "APP_SEARCH_CATEGORY_ICON";

export const APP_SEARCH_CATEGORY_COLOR = "APP_SEARCH_CATEGORY_COLOR";

export const APP_SEARCH_KEY = "APP_SEARCH_KEY";
export const APP_CURRENT_PALYING_COURSE_ID = "APP_CURRENT_PALYING_COURSE_ID";
export const APP_CURRENT_PALYING_COURSE_NAME = "APP_CURRENT_PALYING_COURSE_NAME";
//当前用户
export const APP_CURRENT_SESSION_USER_NAME = "APP_CURRENT_SESSION_USER_NAME";
export const APP_CURRENT_SESSION_EMAIL = "APP_CURRENT_SESSION_EMAIL";
export const APP_CURRENT_LOGIN_USER="APP_CURRENT_LOGIN_USER";

//当前token
export const APP_TOKEN_LOCALSTORAGE_NAME = "APP_TOKEN_LOCALSTORAGE_NAME_FOR_TOKEN";
//当前用户关注的课程
export const APP_CURRENT_USER_FAVORITE_COURSE = "APP_CURRENT_USER_FAVORITE_COURSE";
//当前用户关注的老师
export const APP_CURRENT_USER_FAVORITE_TEACHER = "APP_CURRENT_USER_FAVORITE_TEACHER";
//当前用户关注的学生
export const APP_CURRENT_USER_FAVORITE_STUDENT= "APP_CURRENT_USER_FAVORITE_STUDENT";

//用户关系常量
export const APP_USER_RELATION_STUDENT_TEACHER = 1;
export const APP_USER_RELATION_STUDENT_STUDENT = 2;
export const APP_TARGET_USER_ROLE_STUDENT = 0;
//用户角色常量
export const APP_TARGET_USER_ROLE_ADMIN = 1;
export const APP_TARGET_USER_ROLE_TEACHER = 2;


//用户关系状态常量
export const APP_USER_RELATION_STATUS_OK = 1;
export const APP_USER_RELATION_STATUS_CANCLE = 0;
//用户图片常量
export const APP_MALE_USER_PHOTO_NAME = "/male-default.png";
export const APP_FEMALE_USER_PHOTO_NAME = "/female-default.png";
